class cfgVehicles {
	class OPTRE_S12_SOLA_Jetpack;
	class MM_S12_SOLA_Omni: OPTRE_S12_SOLA_Jetpack {
		scope=2;
		scopeArsenal=2;
		displayName="[MM] S-12 SOLA (Omni)";
		maximumLoad=300;
		mass=60;
		isJetpack=1;
		shortType="omni";
		longType="omni";
		maxCharge=100;
		shortCost=25;
		longCost=50;
		rechargeTime=1;
		rechargeRate=2;
	};
	class MM_S12_SOLA_Vector: OPTRE_S12_SOLA_Jetpack {
		scope=2;
		scopeArsenal=2;
		displayName="[MM] S-12 SOLA (Vector)";
		maximumLoad=300;
		mass=60;
		isJetpack=1;
		shortType="vector";
		longType="vector";
		maxCharge=100;
		shortCost=25;
		longCost=50;
		rechargeTime=1;
		rechargeRate=2;
	};
	class MM_S12_SOLA_VO: OPTRE_S12_SOLA_Jetpack {
		scope=2;
		scopeArsenal=2;
		displayName="[MM] S-12 SOLA (V/O)";
		maximumLoad=300;
		mass=60;
		isJetpack=1;
		shortType="vector";
		longType="omni";
		maxCharge=100;
		shortCost=25;
		longCost=50;
		rechargeTime=1;
		rechargeRate=2;
	};
	class MM_S12_SOLA_OV: OPTRE_S12_SOLA_Jetpack {
		scope=2;
		scopeArsenal=2;
		displayName="[MM] S-12 SOLA (O/V)";
		maximumLoad=300;
		mass=60;
		isJetpack=1;
		shortType="omni";
		longType="vector";
		maxCharge=100;
		shortCost=25;
		longCost=50;
		rechargeTime=1;
		rechargeRate=2;
	};
};